version: '3.7'

services:
    komentar:
        container_name: komentar
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        command: npm run start:dev
        env_file:
            - .env
        networks:
            - webnet

networks:
    webnet: